import lexis from "@julianelda/lexis/oxlint";
import { defineConfig } from "oxlint";

export default defineConfig({
  ...lexis,
  ignorePatterns: [
    "**/node_modules",
    "**/.output",
    "**/.vercel",
    "**/.netlify",
    "**/.wrangler",
    ".svelte-kit",
    "build",
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/.env",
    "**/.env.*",
    "!**/.env.example",
    "!**/.env.test",
    "**/vite.config.js.timestamp-*",
    "**/vite.config.ts.timestamp-*",
  ],
  jsPlugins: ["eslint-plugin-svelte", "eslint-plugin-perfectionist"],
  overrides: [
    {
      files: ["*.svelte", "**/*.svelte"],
      jsPlugins: ["eslint-plugin-svelte"],
      rules: {
        "no-inner-declarations": "off",
        "no-self-assign": "off",
      },
    },
  ],
  rules: {
    ...lexis.rules,
    "svelte/comment-directive": "error",
    "svelte/infinite-reactive-loop": "error",
    "svelte/no-at-debug-tags": "warn",
    "svelte/no-at-html-tags": "error",
    "svelte/no-dom-manipulating": "error",
    "svelte/no-dupe-else-if-blocks": "error",
    "svelte/no-dupe-on-directives": "error",
    "svelte/no-dupe-style-properties": "error",
    "svelte/no-dupe-use-directives": "error",
    "svelte/no-export-load-in-svelte-module-in-kit-pages": "error",
    "svelte/no-immutable-reactive-statements": "error",
    "svelte/no-inner-declarations": "error",
    "svelte/no-inspect": "warn",
    "svelte/no-navigation-without-resolve": "error",
    "svelte/no-not-function-handler": "error",
    "svelte/no-object-in-text-mustaches": "error",
    "svelte/no-raw-special-elements": "error",
    "svelte/no-reactive-functions": "error",
    "svelte/no-reactive-literals": "error",
    "svelte/no-reactive-reassign": "error",
    "svelte/no-shorthand-style-property-overrides": "error",
    "svelte/no-store-async": "error",
    "svelte/no-svelte-internal": "error",
    "svelte/no-unknown-style-directive-property": "error",
    "svelte/no-unnecessary-state-wrap": "error",
    "svelte/no-unused-props": "error",
    "svelte/no-unused-svelte-ignore": "error",
    "svelte/no-useless-children-snippet": "error",
    "svelte/no-useless-mustaches": "error",
    "svelte/prefer-svelte-reactivity": "error",
    "svelte/prefer-writable-derived": "error",
    "svelte/require-each-key": "error",
    "svelte/require-event-dispatcher-types": "error",
    "svelte/require-store-reactive-access": "error",
    "svelte/system": "error",
    "svelte/valid-each-key": "error",
    "svelte/valid-prop-names-in-kit-pages": "error",
    "vitest/require-awaited-expect-poll": "off",
  },
});
